@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTk4MDU3NzJ9.dp5UcDy9wYrhFsG7_FjlGKnFENSdxeIwoMj4-mhSbL4

### User creates

POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Amanda",
  "last_name": "Hale",
  "email": "A@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "A@test.com",
  "password": "password"
}

### trips Index

GET http://localhost:3000/trips
Authorization: Bearer {{jwt}}

### trips Show

GET http://localhost:3000/trips/9
Authorization: Bearer {{jwt}}

### trips create

POST http://localhost:3000/trips
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "There and back again"
}

### trips Update

PATCH http://localhost:3000/trips/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "A hobbit story"
}

### Places create

POST http://localhost:3000/places
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Woods",
  "trip_id": "9",
  "address": "111 Main St",
  "city": "San Fran",
  "zip_code": "93214",
  "longitude": "22.4",
  "latitude": "22.4"
}

### Places Delete

DELETE http://localhost:3000/places/5
Authorization: Bearer {{jwt}}